In [1]:
import pandas as pd

data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

index=['a','b','c','d','e']
series=pd.Series(data,index=index)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [2]:
data={
    'name':['张三','李四','王五','赵六','王二'],
    'age':[18,20,22,24,26],
    'gender':['男','男','女','女','男'],
}
df=pd.DataFrame(data)
print(df)

  name  age gender
0   张三   18      男
1   李四   20      男
2   王五   22      女
3   赵六   24      女
4   王二   26      男

In [4]:
data=[
    ['张三',18,'男'],
    ['李四',20,'男'],
    ['王五',22,'男'],
    ['赵六',24,'女'],
    ['王二',26,'男'],
]
df=pd.DataFrame(data,columns=['name','age','gender'])
print(df)

  name  age gender
0   张三   18      男
1   李四   20      男
2   王五   22      男
3   赵六   24      女
4   王二   26      男

In [5]:
print(df['age'])#age列
print(df.loc[1])#第2行
print(df.iloc[1,1])#第2行第2列

0    18
1    20
2    22
3    24
4    26
Name: age, dtype: int64
name      李四
age       20
gender     男
Name: 1, dtype: object
20

In [7]:

print(df)

  name  age gender
0   张三   18      男
1   李四   20      男
2   王五   22      女
3   赵六   24      女
4   王二   26      男

In [18]:
#增列
df['selery']=df['age']*1000
print(df)

#增行
df.loc['5']=['王二',26,'男',26000]
print(df)

#插入列
#df.insert(2,'height',[1.7,1.8,1.9,1.8,1.7])

  name  age gender  selery
0   张三   18      男   18000
1   李四   20      男   20000
2   王五   22      女   22000
3   赵六   24      女   24000
4   王二   26      男   26000
d   王二   26      男   26000
5   王二   26      男   26000
  name  age gender  selery
0   张三   18      男   18000
1   李四   20      男   20000
2   王五   22      女   22000
3   赵六   24      女   24000
4   王二   26      男   26000
d   王二   26      男   26000
5   王二   26      男   26000

In [ ]:
#删列
""" df.drop('height',axis=1,inplace=True)
print(df) """
#删行
""" df.drop('5',axis=0,inplace=True)
print(df) """

  name  age gender  selery
0   张三   18      男   18000
1   李四   20      男   20000
2   王五   22      女   22000
3   赵六   24      女   24000
4   王二   26      男   26000
d   王二   26      男   26000

In [24]:
df.isnull()
df.dropna()
df.fillna(0)
df.isnull().sum()

name      0
age       0
gender    0
selery    0
dtype: int64

In [ ]:
df1=pd.DataFrame({'name':['张三','李四','王五'],'age':[18,20,22]})
df2=pd.DataFrame({'name':['李四','王二','麻子'],'age':[20,22,28]})
pd.merge(df1,df2,on='name',how='inner')#内合并(交集)

  name  age_x  age_y
0   李四     20     20

In [ ]:
pd.merge(df1,df2,on='name',how='outer')#外合并(并集)

  name  age_x  age_y
0   张三   18.0    NaN
1   李四   20.0   20.0
2   王二    NaN   22.0
3   王五   22.0    NaN
4   麻子    NaN   28.0

In [30]:
pd.merge(df1,df2,on='name',how='left')#左合并
pd.merge(df1,df2,on='name',how='right')#右合并

  name  age_x  age_y
0   李四   20.0     20
1   王二    NaN     22
2   麻子    NaN     28